---
name: Test

on:
  pull_request:
    types:
      - opened
      - re-opened
      - synchronize

jobs:
  test:
    name: Test Docker script
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Test entry point or fail
        run: |
          EXPECTED="SIGNING_CONFIG: --signing-profiles  HelloWorldFunction=TestProfile  HelloAgainFunction=TestProfile"
          OUT=$(bash ./entrypoint.sh ./test/template.yml TestProfile | grep SIGNING_CONFIG)
          [[ $OUT = $EXPECTED ]] || exit 3
          
      - name: Lint the dockerfile
        uses: hadolint/hadolint-action@v2.0.0

